@startuml

CheckersGame - [GameLogic]
[GameLogic] ..> Player1 : use
[GameLogic] ..> Player2 : use
[GameLogic] ..> Board : use
[GameLogic] ..> Rules : use

CheckersGame - [UserInterface]
[UserInterface] ..> GameLogic : use
[UserInterface] ..> Settings : use

CheckersGame - [DataAccess]
[DataAccess] ..> GameLogic : use
[DataAccess] ..> UserInterface : use

@enduml